### ISSUE TITLE
Logo URL is marked as required even when not showing a logo

### ISSUE THREAD

**Issue by AllegroFox** [mozilla/limelight#62] opened 2023-01-25 19:08 UTC
<img width="1304" alt="Screenshot 2023-01-25 at 2 05 29 PM" src="https://user-images.githubusercontent.com/35473317/214659759-a9fb6ead-5c0f-4953-bb76-cf7c34b59964.png">

If we're not showing a logo, we shouldn't need to input an image URL for the JSON to be valid. Height should probably be required however, or at least filled in with a default since it applies whether or not we show the logo.

**Comment by sansarmaske** [comment] 2023-01-26 04:44
![Screenshot 2023-01-26 102622](https://user-images.githubusercontent.com/18899162/214760091-b0631fbe-1e69-4a6f-b30c-7dfd3a28d731.png)
I tried replicating the issue but the URL seems to be disabled and not mandatory when "Show logo?" is unchecked. Could you share the steps to reproduce the issue?

**Comment by brennie** [comment] 2023-01-26 18:02
Turns out this has the same root cause of #56 and was fixed by #58.

**Closed by brennie** 2023-01-26 18:02 UTC
Labels: bug, ux, easyfix
